apiVersion: v1
kind: Service
metadata:
  name: hcs-service
spec:
  selector:
    app: hcs-app
  ports:
  - port: 8000
    targetPort: 8000
    name: http
    protocol: TCP
  - port: 8080
    protocol: TCP
    $patch: delete
